spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/jiudian?useUnicode=true&amp&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
mybatis:
  mapper-locations: classpath:com.new_jiudian.mapper.*.xml